[package]
name = "demo-editor"
version = "0.0.2"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
# This is a demo crate, we shouldn't publish it
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hydrate = { path = "../hydrate", version = "0.0.2", features = ["editor"] }
demo-plugins = { path = "../demo-plugins" }

egui = "0.24.1"
eframe = { version = "0.24.1", default-features = false, features = ["default_fonts", "glow", "persistence"] }

log = "0.4.14"
env_logger = "0.9.0"

profiling = "1.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = { default-features = false, version = "1.0.85", features = ["std"] }


[features]
default = ["profiling/profile-with-tracy"]